### ISSUE TITLE
Installation Failure on Ubuntu 16.04.6

### ISSUE THREAD

**Issue by Richard57** [silnrsi/oxttools#5]
With Python Version 2.7.12 on Ubuntu 16.04.6, the installation command `python setup.py build` fails with traceback:

```
Traceback (most recent call last):
  File "setup.py", line 8, in <module>
    ez_setup.use_setuptools()
  File "/home/richard/dicts/oxttools/ez_setup.py", line 170, in use_setuptools
    return _do_download(version, download_base, to_dir, download_delay)
  File "/home/richard/dicts/oxttools/ez_setup.py", line 130, in _do_download
    import setuptools
  File "build/bdist.linux-i686/egg/setuptools/__init__.py", line 11, in <module>
  File "build/bdist.linux-i686/egg/setuptools/extension.py", line 8, in <module>
  File "build/bdist.linux-i686/egg/setuptools/dist.py", line 19, in <module>
  File "build/bdist.linux-i686/egg/pkg_resources/__init__.py", line 90, in <module>
AttributeError: 'module' object has no attribute '_vendor'
```

**Comment by DavidLRowe** [comment]
This is probably too late to help, but that error would indicate that the setuptools package is not installed. 

Since the time this issue was raised, support for Python 2 has been dropped.
